### PR TITLE
More challenges

### PR DESCRIPTION
**Pull request by c-martinez**
Challenges for lessons 03 and 04 done.

### CODE REVIEW

**Comment by c-martinez** [comment]
@mkuzak -- you may want to check if it all renders beautifully before merging.

**Comment by drjwbaker** [comment]
Can someone look at this? (I'm not sure who is maintaining the lesson, @mpfl @mkuzak?)

**Comment by mpfl** [comment]
I did put my hand up to maintain this lesson, but it looks like I don't have write access to this repo. @mkuzak is probably in a better position to resolve this.

**Comment by c-martinez** [comment]
I had also volunteered for maintainer, although it would make sense for someone other than me to have a look at this PR before merging. Spoke with @mkuzak yesterday and he promised to have a look soon.

**Comment by mkuzak** [comment]
Sorry for my sluggishness. Merged.

**Comment by mkuzak** [comment]
I cannot add @c-martinez and @mpfl to the library team, they have to be first in the data-lessons organization. @tracykteal can you add them?

**Pull request merged**
